# Generated by Django 4.2.7 on 2024-02-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
